@invertase/ci review v3
firebase/extensions pull request #1341
Opened 2022-12-07 12:46 UTC by cabljac

2022-12-15 15:32 UTC, dackers86 requested changes

2022-12-15 15:32 UTC, dackers86 commented on delete-user-data/functions/__tests__/search.test.ts
> +  describe.skip("searches on top level collection documents", () => {
May also need to be resolved.

2022-12-15 15:32 UTC, dackers86 commented on delete-user-data/functions/__tests__/search.test.ts
> +    test.skip("can delete a document with a field value named {uid}", async () => {
.skip

2022-12-15 15:32 UTC, dackers86 commented on delete-user-data/functions/__tests__/search.test.ts
> +  describe.skip("sub collection", () => {
.skip

2022-12-15 16:17 UTC, cabljac commented on .github/workflows/test.yml
> +          cache-dependency-path: "**/package-lock.json"
if packages are updated then i believe it changes a package-lock, which is a dep path and then things would be updated. it doesn't cache node-modules as far as i understand, it's doing something globally. I'll provide the docs reference

2022-12-15 16:18 UTC, cabljac commented on .github/workflows/test.yml
> +      max-parallel: 2
node 14 and node 16 jobs run in different containers i believe, and so wouldn't clash

2022-12-15 16:19 UTC, cabljac commented on auth-mailchimp-sync/functions/jest.config.js
> +  testPathIgnorePatterns: process.env.CI_TEST === "true" ? ["e2e"] : [],
so the test ignore paths are all set to match any `e2e` in CI, but we can probably remove this for things that aren't BQ related. It was more related to "e2e tests require a google cloud project" in BQ

2022-12-22 10:42 UTC, dackers86 commented on .github/workflows/test.yml
> +          cache-dependency-path: "**/package-lock.json"
Ok, seems good for improving performance:

Docs ref: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md

2022-12-22 11:27 UTC, dackers86 approved these changes

2022-12-22 11:29 UTC, merged