feat(storage-resize-images): add standardised EventArc events
firebase/extensions pull request #1424
Opened 2023-02-01 10:52 UTC by cabljac

2023-03-06 15:45 UTC, cabljac commented on storage-resize-images/functions/src/index.ts
> +    await events.recordCompletionEvent({ context });
context i think, according to the completion event spec: [see here?](https://github.com/firebase/extensions/pull/1424/files/4844a5a4bbb46dacca00d165a72e3708ce60bec1#diff-cf28a2adb596945c2977f32cf00850df05eb5fee813b0cd976d4e9ead5250da3R355)

2023-10-18 10:34 UTC, dackers86 approved these changes

2023-10-18 10:34 UTC, merged

2025-01-06 11:59 UTC, maihengxing999 commented
feat(*): add standardised EventArc events

2025-01-06 13:47 UTC, raw1359 approved these changes

2025-01-10 23:06 UTC, maihengxing999 commented
next

2025-02-12 23:42 UTC, maihengxing999 commented
#1424

2025-06-14 01:40 UTC, bigflash02uk requested changes
Delete off my system

2026-01-10 03:04 UTC, zjxdnvpzpn-beep reviewed
@

2026-05-22 00:22 UTC, sumikn233-al approved these changes