docs(storage-resize-image): update the doc for output options
firebase/extensions pull request #1905
Opened 2024-01-09 17:31 UTC by renuvkelkar

2024-01-10 09:42 UTC, cabljac approved these changes
looks good to me!

2024-01-11 11:43 UTC, pr-Mais requested changes

2024-01-11 11:43 UTC, pr-Mais commented on storage-resize-images/README.md
> +* Output options for selected formats: Provide a optional output option stringified object containing Sharp Output Options for selected image types conversion. eg. {"jpeg": { "quality": 5, "chromaSub
```suggestion
* Output options for selected formats: Provide an optional output option stringified object containing Sharp Output Options for selected image types conversion. eg. `{"jpeg": { "quality": 5, "chromaSubsampling": "4:4:4" }, "png": { "palette": true }}` and `{"png":{"compressionLevel":9}}`. The `"compressionLevel": 9` specifies the level of compression for PNG images. Higher numbers here indicate greater compression, leading to smaller file sizes at the cost of potentially increased processing time and possible loss of image quality. 
```

2024-01-16 18:25 UTC, pr-Mais requested changes

2024-01-16 18:25 UTC, pr-Mais commented on storage-resize-images/extension.yaml
> +      Provide an optional output option stringified object containing Sharp Output Options for selected image types conversion. eg. `{"jpeg": { "quality": 5, "chromaSubsampling": "4:4:4" }, "png": {
```suggestion
      Provide an optional output option as a stringified object containing Sharp Output Options for selected image types conversion. eg. `{"jpeg": { "quality": 5, "chromaSubsampling": "4:4:4" }, "png": { "palette": true }}` and `{"png":{"compressionLevel":9}}`. The `"compressionLevel": 9` specifies the level of compression for PNG images. Higher numbers here indicate greater compression, leading to smaller file sizes at the cost of potentially increased processing time and possible loss of image quality.  
```

2024-01-16 18:31 UTC, pr-Mais commented
Can you please add more explanation on how to use `fit` in the options? To resolve this issue #1891

2024-01-17 13:30 UTC, pr-Mais requested changes

2024-01-17 13:30 UTC, pr-Mais commented on storage-resize-images/extension.yaml
> +      Provide a optional output option stringified object containing Sharp Output Options for selected image types conversion. eg. `{ failOnError: false, limitInputPixels: true, fit: 'inside' }` The`
```suggestion
      Provide an optional output option stringified object containing Sharp Output Options for selected image types conversion. eg. `{ "failOnError: false, "limitInputPixels": true, "fit: "inside" }` The`"fit": "inside"` option ensures the image fits within given dimensions, maintaining aspect ratio, scaling down as needed without cropping or distortion. Learn more about [`Sharp constructor options`](https://sharp.pixelplumbing.com/api-resize#resize).
```

2024-01-17 13:30 UTC, pr-Mais commented on storage-resize-images/extension.yaml
> +      Provide a optional output option stringified object containing Sharp Output Options for selected image types conversion. eg. `{ failOnError: false, limitInputPixels: true, fit: 'inside' }` The`
It should be a JSON string hence keys must be inside quotes.

2024-01-17 15:07 UTC, pr-Mais commented
@jauntybrain do you think we can add a validation regex for JSON strings?

2024-01-17 15:55 UTC, jauntybrain commented
> @jauntybrain do you think we can add a validation regex for JSON strings?

I doubt it. We would need complex nested validation to validate JSON, which we cannot do with `extension.yaml`.
This also might cause new edge cases -  I would not risk it

2024-01-17 16:03 UTC, pr-Mais requested changes

2024-01-17 16:03 UTC, pr-Mais commented on storage-resize-images/extension.yaml
> +      Provide an optional output option stringified object containing Sharp Output Options for selected image types conversion. eg. `{ "failOnError": false, "limitInputPixels": true, "fit": "inside"
The description here is inaccurate, it's not "output options", try to make it more clear

2024-01-31 09:49 UTC, pr-Mais commented
@jauntybrain can you resolve the conflict

2024-01-31 14:50 UTC, pr-Mais approved these changes

2024-01-31 14:50 UTC, merged