docs(firestore-send-email): update the doc for handlebar
firebase/extensions pull request #1922
Opened 2024-01-15 17:35 UTC by renuvkelkar

fixes https://github.com/firebase/extensions/issues/1522

2024-01-16 18:36 UTC, pr-Mais requested changes

2024-01-16 18:36 UTC, pr-Mais commented on firestore-send-email/extension.yaml
> +       This ensures that Handlebars doesn't perform additional escaping or modifications to the URL. For example, `<img src="{{{picPath}}}" alt="PDF Attachment">`
```suggestion
      This ensures that Handlebars doesn't perform additional escaping or modifications to the URL. For example, `<img src="{{{picPath}}}" alt="PDF Attachment">`
```

2024-01-16 20:07 UTC, renuvkelkar commented on firestore-send-email/extension.yaml
> +      It's recommended to use triple curly braces `{{{  }}}` in your Handlebars templates when the substitution value is a URL or otherwise sensitive to html escaping.
I have updated the doc.

2024-01-29 18:33 UTC, jauntybrain approved these changes

2024-01-30 09:49 UTC, pr-Mais approved these changes

2024-01-30 09:49 UTC, merged