feat(storage-resize-images): add parameter REGENERATE_TOKEN
firebase/extensions pull request #1935
Opened 2024-01-29 17:31 UTC by jauntybrain

Allow users to decide whether the resized image will have the same access token as the old one, or a newly generated one.

Fixes #1925

2024-01-30 09:55 UTC, pr-Mais requested changes

2024-01-30 09:55 UTC, pr-Mais commented on storage-resize-images/extension.yaml
> +    required: true
i don't think this should be required, it might cause a breaking change for existing users, change it to none-required.

2024-01-31 09:50 UTC, pr-Mais approved these changes
LGTM

2024-01-31 10:03 UTC, merged

2024-02-06 21:32 UTC, almogtovim commented
Can I use it already?