docs(firestore-counter): android client example
firebase/extensions pull request #541
Opened 2020-12-21 12:35 UTC by russellwheatley

partially fixes #520 by updating `POSTINSTALL.md` with android code sample on how to use the `FirestoreShardedCounter`.

2021-01-11 19:53 UTC, kevinthecheung requested changes

2021-01-11 19:53 UTC, kevinthecheung commented on firestore-counter/POSTINSTALL.md
> +1. Follow the Firebase android setup [guide](https://firebase.google.com/docs/android/setup) in order to use Firebase in your app.
```suggestion
1. Follow the steps in [Add Firebase to your Android project](https://firebase.google.com/docs/android/setup) to use Firebase in your app.
```

2021-01-11 19:53 UTC, kevinthecheung commented on firestore-counter/POSTINSTALL.md
> +2. Copy and paste the sample [code](https://github.com/firebase/extensions/blob/next/firestore-counter/clients/android/src/main/java/com/firebase/firestore/counter/FirestoreShardedCounter.java) and c
```suggestion
2. Copy the [sample code](https://github.com/firebase/extensions/blob/next/firestore-counter/clients/android/src/main/java/com/firebase/firestore/counter/FirestoreShardedCounter.java) to the directory in which you want to use the `FirestoreShardedCounter` instance.
```

2021-01-12 17:31 UTC, kevinthecheung approved these changes

2021-02-23 13:01 UTC, Salakar approved these changes

2021-02-24 16:17 UTC, jhuleatt commented on firestore-counter/POSTINSTALL.md
> +2.  Use the client sample in your code to increment counters. The code snippet below shows an example of how to use it. To see the full reference implementation, refer to the sample's TypeScript [sou
```suggestion
1.  Use the client sample in your code to increment counters. The code snippet below shows an example of how to use it. To see the full reference implementation, refer to the sample's TypeScript [source code](https://github.com/firebase/extensions/blob/master/firestore-counter/clients/web/src/index.ts).
```

2021-02-24 16:18 UTC, jhuleatt approved these changes

2021-03-02 22:49 UTC, merged