feat(firestore-bigquery-export): big query partitioned tables
firebase/extensions pull request #581
Opened 2021-02-01 17:38 UTC by russellwheatley

Fixes https://github.com/firebase/extensions/issues/316

1. Tested creating fresh time partitioned BigQuery tables without a problem
2. Tested "updating" the extension whilst pointing to existing non-partitioned BigQuery tables. 

The feature is backwards compatible. The BigQuery tracker package always checks if the table exists before setting the `timePartitioning` metadata for the raw changelog table and the latest view table.

In the future, we may also wish to update the `gen-schema-view` script to also allow time partitioning, but I suggest we wait for this to land and settle.

2021-02-16 13:54 UTC, dackers86 approved these changes

2021-02-23 12:26 UTC, Salakar commented on firestore-bigquery-export/extension.yaml
> +      - label: no table partitioning
```suggestion
      - label: none
```

2021-02-23 12:28 UTC, Salakar commented on firestore-bigquery-export/extension.yaml
> +    default: false
```suggestion
        value: NONE
    default: NONE
```

2021-02-23 12:30 UTC, Salakar requested changes
LGTM with minor options naming changes

2021-02-23 12:30 UTC, Salakar approved these changes

2021-02-23 17:02 UTC, jhuleatt commented on firestore-bigquery-export/extension.yaml
> +    required: true
@kevinthecheung can you please give this new param a review?

2021-03-02 23:01 UTC, jhuleatt commented on firestore-bigquery-export/extension.yaml
> +    required: true
Kevin is OOO. This looks good to me.

2021-03-02 23:01 UTC, jhuleatt approved these changes

2021-03-02 23:09 UTC, merged