fix(firestore-send-email) added fallback for finding email templates
firebase/extensions pull request #713
Opened 2021-07-30 09:49 UTC by dackers86

2021-08-10 07:43 UTC, Ehesp requested changes

2021-08-10 07:43 UTC, Ehesp commented on firestore-send-email/functions/src/templates.ts
> +    const query = this.collection.where("name", "==", name).get();
```js
return this.collection.where("name", "==", name).get().then(t => !t.empty);
```

2021-08-10 07:43 UTC, Ehesp commented on firestore-send-email/functions/src/templates.ts
> +  checkTemplateExists = async (name) => {
Doesn't need to be `async`.

2021-08-10 07:43 UTC, Ehesp commented on firestore-send-email/functions/src/templates.ts
> +          new Error(`tried to render non-existent template '${name}'`)
`tried` -> `Tried`.

2021-08-10 09:46 UTC, Ehesp approved these changes

2021-08-18 20:18 UTC, huangjeff5 commented
Can we remove the .js files for this extension?

2021-08-18 20:28 UTC, merged