feat(*): add Taiwan and Singapore Cloud Function Locations
firebase/extensions pull request #720
Opened 2021-08-13 19:47 UTC by rosariopfernandes

This PR should:
- update firebase-admin to `9.11.0`
- update firebase-functions to `3.15.3`
- add Taiwan (`asia-east1`) and Singapore (`asia-southeast1`) to the list of available Cloud Function Locations for every extension.

2021-08-17 08:57 UTC, dackers86 requested changes

2021-08-17 08:57 UTC, dackers86 commented on rtdb-limit-child-nodes/functions/package.json
> +    "firebase-admin": "^9.11.0",
Updating these references causes the following build issues....

```js
src/index.ts(32,33): error TS2339: Property 'path' does not exist on type 'Reference'.
src/index.ts(43,39): error TS2339: Property 'path' does not exist on type 'Reference'.
src/index.ts(45,38): error TS2339: Property 'path' does not exist on type 'Reference'.
src/index.ts(47,36): error TS2339: Property 'path' does not exist on type 'Reference'.
```

It seems path was removed at some point before the `v9` release

2021-08-18 08:55 UTC, dackers86 commented
hi @rosariopfernandes.

Following the above feedback, would it be possible  to remove the dependency updates and to just include the additional location code changes for this PR.

In addition, could you create a separate PR for the dependency updates, this allows a seperation of concerns for the PRs and would allow this particular PR to be quickly approved.

Thanks!

2021-09-02 21:05 UTC, rosariopfernandes commented
Hey @dackers86
Sorry for the delayed response here. Had a busy week and missed the notifications for this PR...
I see you've already sent separate PRs to fix the build here. Thanks for that!
Is there any action still required from me?

2021-10-05 16:14 UTC, dackers86 commented
HI @rosariopfernandes 

Apologies, I missed your message! No more action needed, in terms of the updated dependencies for the extension modules we have decided to update these as separate PRs as noted above. 

Updating the dependencies can be moved to the individual PRs so the location update is now ready for the next release.

2021-10-06 11:34 UTC, dackers86 commented
Adding to blocking column. Happy to keep this open as a reference to the linked PRs.

2023-10-18 12:52 UTC, dackers86 commented
Closing as configurable location params have now been removed from extensions in this repository.

2023-10-18 12:52 UTC, closed without merging