feat(firestore-bigquery-export): added JSON data type to the default bigquery schema
firebase/extensions pull request #919
Opened 2022-03-16 10:14 UTC by dackers86

The BigQuery extension currently uses a `stringified` JSON object to store data when synching from Firestore. This PR prepares for when a JSON type becomes available.

A new JSON datatype is currently in preview and can be tracked here https://cloud.google.com/bigquery/docs/reference/standard-sql/json-data

- [x] Update the default schema to use a JSON datatype
- [ ] Ensure new tables are generated with the new datatype

2022-10-07 21:11 UTC, IchordeDionysos commented
@dackers86 when is it planned to merge this PR? Sounds like a helpful addition 😍

2022-10-08 08:35 UTC, IchordeDionysos requested changes
Nice work, but there are some missing pieces, especially the latest view won't work anymore when using the `JSON` data type

2022-10-08 08:35 UTC, IchordeDionysos commented on firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/schema.ts
>        name: "data",
The field `path_params` should also be made a JSON object depending on the users selection.

2022-10-08 08:35 UTC, IchordeDionysos commented on firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts
>        const latestSnapshot = latestConsistentSnapshotView(
The `latest` BigQuery view also needs to be adjusted as it's not possible to group a JSON column.

This is what comes up when you have `data` as a `JSON` field, with the auto-created`collection_raw_latest` view.
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/10195482/194698281-561768c2-e01b-48aa-b3ff-d6333118fea9.png">

2022-10-10 13:17 UTC, dackers86 commented
Thanks [IchordeDionysos](https://github.com/IchordeDionysos). Now that the JSON updated is out of it's original `preview` status we can resume development on this. The next steps will be to address the issues you have pointed out in terms of the `views` and `path_params`.

2022-11-09 14:18 UTC, nfarina commented
I was able to make this work by using `SELECT …, ARRAY_AGG(data)[offset(0)] as data,` instead of attempting to `GROUP BY data` since grouping by native JSON type is still unsupported.

However, this removes most of the advantages of the JSON type! When querying the resulting View, the entire `data` column is loaded (and billed) instead of a subset. For instance `SELECT data.age FROM latest` will read the same number of bytes as `SELECT data FROM latest`.

This is as opposed to `SELECT data.age FROM changelog" which only bills for the `age` column (since native JSON types are spread out into native subcolumns at ingestion time).

I don't know enough about BigQuery to suggest an alternative strategy, but I really hope there is a way to have our cake and eat it too here.

2023-01-03 11:26 UTC, dackers86 commented
Moving this back to `under consideration` for planning.  This PR was an initial start but we need to consider and plan how this fits into the overall BQ schema and development.

2023-10-30 10:02 UTC, basvandorst commented
We manually changed the datatype of the changelog-table to JSON and had indeed to deal with the same group by issue. 

We fixed it in this way: 
```
WITH RankedData AS (
  SELECT
    document_name,
    document_id,
    timestamp,
    event_id,
    operation,
    data,
    path_params,
    ROW_NUMBER() OVER(PARTITION BY document_name ORDER BY timestamp DESC) AS row_num
  FROM `collection`
)
SELECT
  document_name,
  document_id,
  timestamp,
  event_id,
  operation,
  data,
  path_params
FROM RankedData
WHERE row_num = 1 
```

Don't know enough about the inner workings /performance impact of BQ but for us it works fine!

2024-08-14 07:44 UTC, tiagosilveiransj commented
Any updates on this? It would be very useful.

2026-05-08 10:51 UTC, cabljac commented
closing as stale

2026-05-08 10:51 UTC, closed without merging