chore(*) added documentation folder for extensions
firebase/extensions pull request #961
Opened 2022-05-03 15:17 UTC by dackers86

Storage/implementation of official extensions documentation

2022-05-10 17:22 UTC, Salakar commented on .docs/firestore-send-email/ManageDeliveryStatus.md
> +Status: Approved
Remove

2022-05-10 17:22 UTC, Salakar commented on .docs/firestore-send-email/SMTPConnectionURL.md
> +Status: In Progress
Remove

2022-05-10 17:22 UTC, Salakar commented on .docs/firestore-send-email/UseHandlebarsTemplates.md
> +Status: Approved
Remove

2022-05-11 12:04 UTC, Salakar commented
Lets rename `.docs` to `docs` also

2022-05-17 16:38 UTC, i14h commented
@kevinthecheung can you please take a look at these docs? we intend to merge them with firebase documentation as well

2022-05-17 16:39 UTC, Ehesp requested changes

2022-05-17 16:39 UTC, Ehesp commented on docs/firestore-send-email/GetStarted.md
> +```jsx
`js` vs `jsx`

2022-05-18 23:36 UTC, kevinthecheung requested changes

2022-05-19 08:21 UTC, dackers86 commented
Thanks @kevinthecheung. Suggestions committed.

2022-06-29 17:41 UTC, kevinthecheung approved these changes

2022-06-30 08:19 UTC, dackers86 commented on docs/firestore-bigquery-export/CrossProjectSupport .md
> +# Cross-Project Support
Thanks!

2022-07-28 10:31 UTC, Ehesp approved these changes

2022-09-26 10:50 UTC, merged